[package]
name = "ridi-router-tiles"
version.workspace = true
edition.workspace = true

[features]
default = []
debug-polygons = []

[dependencies]
anyhow.workspace = true
bincode.workspace = true
bytemuck.workspace = true
chrono.workspace = true
geo.workspace = true
hex.workspace = true
memmap2.workspace = true
osmpbfreader.workspace = true
rayon.workspace = true
redb.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tracing.workspace = true
rstar.workspace = true
smartstring.workspace = true
wide.workspace = true
num-traits.workspace = true
ridi-router-common = { path = "../ridi-router-common" }

[dev-dependencies]
ridi-router-routing = { path = "../ridi-router-routing" }
rusty-fork.workspace = true
tracing-subscriber.workspace = true
