[package]
name = "moto-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
geo-types = "0.7.13"
gpx = "0.10.0"
serde = "1.0.201"
serde_derive = "1.0.201"
serde_json = "1.0.117"
