[package]
name = "ridi-router"
version = "0.1.4"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.9"
geo = "0.28.0"
gpx = "0.10.0"
# json-tools = "1.1.2"
json-tools = { git = "https://github.com/tomsjansons/json-tools.git", branch = "value-pairs" }
osmpbfreader = "0.16.1"
rand = "0.8.5"
rayon = "1.10.0"
serde = "1.0.201"
serde_derive = "1.0.201"
serde_json = "1.0.117"

[dev-dependencies]
rusty-fork = "0.3.0"
