[package]
name = "moto-router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.9"
geo = "0.28.0"
gpx = "0.10.0"
json-tools = "1.1.2"
rand = "0.8.5"
serde = "1.0.201"
serde_derive = "1.0.201"
serde_json = "1.0.117"
