services:
  db:
    image: postgis/postgis:17-3.5-alpine
    restart: unless-stopped
    ports:
      - "54227:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./map-data/:/map-data

volumes:
  db-data:
