services:
  martin:
    image: ghcr.io/maplibre/martin:v0.16.0
    restart: unless-stopped
    ports:
      - "3027:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db/db
    depends_on:
      - db
    command: --webui enable-for-all --default-srid=4326

  db:
    image: postgis/postgis:17-3.5-alpine
    restart: unless-stopped
    ports:
      - "54227:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./map-data/:/map-data

volumes:
  db-data:
