[package]
name = "ridi-app"
version = "0.8.6"
edition = "2021"

[[bin]]
name = "app"
path = "src/main.rs"

[dependencies]
macroquad = "=0.4.14"
anyhow = "1.0.95"
geozero = { version = "=0.14.0", default-features = false, features = ["with-mvt"] }
i_triangle = "0.34"
memmap2 = "0.9"
pmtiles = { version = "=0.15.0", default-features = false, features = ["http-async", "reqwest-rustls-tls"] }
tokio = { version = "1", features = ["rt", "macros"] }
ron = "0.8"
serde = { version = "1.0.201", features = ["derive"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3"
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["Window", "Navigator", "Geolocation"] }

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"

[target.'cfg(target_os = "ios")'.dependencies]
objc = { package = "objc-rs", version = "0.2" }

[package.metadata.android]
package_name = "bike.ridi.app"
label = "Ridi"
assets = "assets"
fullscreen = true
build_targets = ["aarch64-linux-android"]

[[package.metadata.android.bin]]
name = "app"
package_name = "bike.ridi.app"
label = "Ridi"
assets = "assets"
fullscreen = true

[package.metadata.android.application_attributes]
"android:debuggable" = "true"

[package.metadata.android.activity_attributes]
"android:exported" = "true"

[[package.metadata.android.permission]]
name = "android.permission.INTERNET"

[[package.metadata.android.permission]]
name = "android.permission.ACCESS_FINE_LOCATION"

[[package.metadata.android.permission]]
name = "android.permission.ACCESS_COARSE_LOCATION"
