import type { MapProps } from "@maplibre/maplibre-react-native";

const PMTILES_URL = "https://maps.ridi.bike/map.pmtiles";
const SOURCE_ID = "protomaps-basemap-v4";
const SOURCE_LAYER = {
  boundaries: "boundaries",
  earth: "earth",
  landuse: "landuse",
  places: "places",
  roads: "roads",
  water: "water",
} as const;

export const ridiMapStyle: MapProps["mapStyle"] = {
  version: 8,
  name: "Ridi",
  glyphs: "https://fonts.openmaptiles.org/{fontstack}/{range}.pbf",
  sources: {
    [SOURCE_ID]: {
      type: "vector",
      url: `pmtiles://${PMTILES_URL}`,
      attribution: "© OpenStreetMap contributors © Protomaps",
    },
  },
  layers: [
    {
      id: "background",
      type: "background",
      paint: { "background-color": "#386666" },
    },
    {
      id: "water_ocean_fill",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.water,
      filter: ["==", ["get", "kind"], "ocean"],
      paint: { "fill-color": "#386666" },
    },
    {
      id: "earth_fill",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.earth,
      filter: ["==", ["get", "kind"], "earth"],
      paint: { "fill-color": "#DCB372" },
    },
    {
      id: "landuse_forest",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.landuse,
      filter: [
        "in",
        ["get", "kind"],
        ["literal", ["forest", "nature_reserve", "wood"]],
      ],
      paint: { "fill-color": "#535D36" },
    },
    {
      id: "landuse_grass",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.landuse,
      filter: [
        "in",
        ["get", "kind"],
        [
          "literal",
          [
            "camp_site",
            "cemetery",
            "dog_park",
            "garden",
            "golf_course",
            "grass",
            "meadow",
            "playground",
            "scrub",
            "zoo",
          ],
        ],
      ],
      paint: { "fill-color": "#A39245" },
    },
    {
      id: "landuse_industrial_concrete",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.landuse,
      filter: [
        "in",
        ["get", "kind"],
        [
          "literal",
          [
            "aerodrome",
            "bare_rock",
            "commercial",
            "hospital",
            "hotel",
            "industrial",
            "runway",
            "supermarket",
            "taxiway",
            "university",
            "townhall",
          ],
        ],
      ],
      paint: { "fill-color": "#826454" },
    },
    {
      id: "landuse_farm",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.landuse,
      filter: ["in", ["get", "kind"], ["literal", ["farmland", "farmyard"]]],
      paint: { "fill-color": "#BC9250" },
    },
    {
      id: "landuse_park",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.landuse,
      filter: ["in", ["get", "kind"], ["literal", ["park", "national_park"]]],
      paint: { "fill-pattern": "park-dot" },
    },
    {
      id: "landuse_military_fill",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.landuse,
      filter: ["==", ["get", "kind"], "military"],
      paint: { "fill-pattern": "military-hatch" },
    },
    {
      id: "landuse_residential",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.landuse,
      filter: ["in", ["get", "kind"], ["literal", ["residential", "school"]]],
      paint: { "fill-color": "#CA9B1B" },
    },
    {
      id: "water_lake",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.water,
      filter: [
        "any",
        ["==", ["get", "kind"], "lake"],
        [
          "in",
          ["get", "kind_detail"],
          ["literal", ["canal", "dock", "lake", "reservoir"]],
        ],
        ["in", ["get", "kind"], ["literal", ["other", "water"]]],
      ],
      paint: { "fill-color": "#386666" },
    },
    {
      id: "water_playa",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.water,
      filter: ["==", ["get", "kind"], "playa"],
      paint: { "fill-color": "#DCB372" },
    },
    {
      id: "water_rivers_fill",
      type: "fill",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.water,
      filter: ["in", ["get", "kind_detail"], ["literal", ["river"]]],
      paint: { "fill-color": "#386666" },
    },
    {
      id: "water_stream_lines",
      type: "line",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.water,
      filter: [
        "in",
        ["get", "kind_detail"],
        ["literal", ["canal", "ditch", "drain", "stream"]],
      ],
      paint: { "line-color": "#386666", "line-width": 1.2 },
    },
    {
      id: "highway_road_casing",
      type: "line",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.roads,
      filter: ["==", ["get", "kind"], "highway"],
      paint: {
        "line-color": "#9E541C",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          4,
          0.9,
          10,
          2.4,
          15,
          4.4,
        ],
      },
    },
    {
      id: "major_roads_casing",
      type: "line",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.roads,
      filter: ["==", ["get", "kind"], "major_road"],
      paint: {
        "line-color": "#9E541C",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          5,
          0.7,
          10,
          2,
          15,
          3.6,
        ],
      },
    },
    {
      id: "minor_roads_casing",
      type: "line",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.roads,
      filter: ["in", ["get", "kind"], ["literal", ["minor_road", "other"]]],
      paint: {
        "line-color": "#9D541C",
        "line-width": ["interpolate", ["linear"], ["zoom"], 10, 0.9, 15, 2.4],
      },
    },
    {
      id: "highway_road",
      type: "line",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.roads,
      filter: ["==", ["get", "kind"], "highway"],
      paint: {
        "line-color": "#C76B24",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          4,
          0.45,
          10,
          1.6,
          15,
          3.2,
        ],
      },
    },
    {
      id: "major_roads",
      type: "line",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.roads,
      filter: ["==", ["get", "kind"], "major_road"],
      paint: {
        "line-color": "#C76B24",
        "line-width": [
          "interpolate",
          ["linear"],
          ["zoom"],
          5,
          0.35,
          10,
          1.3,
          15,
          2.6,
        ],
      },
    },
    {
      id: "minor_roads",
      type: "line",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.roads,
      filter: ["in", ["get", "kind"], ["literal", ["minor_road", "other"]]],
      paint: {
        "line-color": "#C66A23",
        "line-width": ["interpolate", ["linear"], ["zoom"], 10, 0.55, 15, 1.6],
      },
    },
    {
      id: "path_roads",
      type: "line",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.roads,
      filter: ["==", ["get", "kind"], "path"],
      paint: {
        "line-color": "#875D2B",
        "line-width": ["interpolate", ["linear"], ["zoom"], 10, 0.75, 15, 2],
        "line-dasharray": [3.5, 1.5],
      },
    },
    {
      id: "rail_roads",
      type: "line",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.roads,
      filter: ["==", ["get", "kind"], "rail"],
      paint: {
        "line-color": "#75666B",
        "line-width": 2,
        "line-dasharray": [6, 4],
      },
    },
    {
      id: "country_boundaries",
      type: "line",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.boundaries,
      filter: ["==", ["get", "kind"], "country"],
      paint: {
        "line-color": "#8F8F8F",
        "line-width": 1.2,
        "line-dasharray": [4, 2],
      },
    },
    {
      id: "city_dots",
      type: "circle",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.places,
      filter: ["==", ["get", "kind_detail"], "city"],
      paint: {
        "circle-color": "#3F3F3F",
        "circle-radius": 2,
        "circle-stroke-color": "#FFFFFF",
        "circle-stroke-width": 0.75,
      },
    },
    {
      id: "country_names",
      type: "symbol",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.places,
      filter: ["==", ["get", "kind"], "country"],
      layout: {
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        "text-font": ["Open Sans Bold"],
        "text-size": 15,
        "text-transform": "uppercase",
      },
      paint: {
        "text-color": "#4C4C4C",
        "text-halo-color": "#DCB372",
        "text-halo-width": 2,
      },
    },
    {
      id: "city_names",
      type: "symbol",
      source: SOURCE_ID,
      "source-layer": SOURCE_LAYER.places,
      filter: ["==", ["get", "kind_detail"], "city"],
      layout: {
        "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
        "text-font": ["Open Sans Regular"],
        "text-size": 13,
        "text-offset": [0.4, 0],
      },
      paint: {
        "text-color": "#333333",
        "text-halo-color": "#DCB372",
        "text-halo-width": 1.75,
      },
    },
  ],
};
