apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

buildscript {
  ext.safeExtGet = { prop, fallback ->
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
  }
}

android {
  namespace 'bike.ridi.modules.router'
  compileSdkVersion safeExtGet('compileSdkVersion', 36)

  defaultConfig {
    minSdkVersion safeExtGet('minSdkVersion', 24)
    targetSdkVersion safeExtGet('targetSdkVersion', 36)
  }

  sourceSets {
    main {
      java.srcDirs = ['src/main/java']
      jniLibs.srcDirs = ['src/main/jniLibs']
    }
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${safeExtGet('kotlinVersion', '2.1.20')}"
  implementation "net.java.dev.jna:jna:5.13.0@aar"
}
