use serde_derive::Deserialize;
use serde_derive::Serialize;

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OsmData {
    pub version: f64,
    pub generator: String,
    pub osm3s: Osm3s,
    pub elements: Vec<Element>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Osm3s {
    #[serde(rename = "timestamp_osm_base")]
    pub timestamp_osm_base: String,
    pub copyright: String,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Element {
    #[serde(rename = "type")]
    pub type_field: String,
    pub id: u64,
    pub lat: Option<f64>,
    pub lon: Option<f64>,
    pub tags: Option<Tags>,
    #[serde(default)]
    pub nodes: Vec<u64>,
    #[serde(default)]
    pub members: Vec<Member>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Tags {
    pub restriction: Option<String>,
    #[serde(rename = "type")]
    pub type_field: Option<String>,
    #[serde(rename = "restriction:conditional")]
    pub restriction_conditional: Option<String>,
    pub except: Option<String>,
    #[serde(rename = "restriction:hgv")]
    pub restriction_hgv: Option<String>,
    #[serde(rename = "hour_off")]
    pub hour_off: Option<String>,
    #[serde(rename = "hour_on")]
    pub hour_on: Option<String>,
    #[serde(rename = "restriction:motorcar")]
    pub restriction_motorcar: Option<String>,
    pub highway: Option<String>,
    pub foot: Option<String>,
    pub lanes: Option<String>,
    pub oneway: Option<String>,
    #[serde(rename = "int_ref")]
    pub int_ref: Option<String>,
    #[serde(rename = "lanes:backward")]
    pub lanes_backward: Option<String>,
    #[serde(rename = "lanes:forward")]
    pub lanes_forward: Option<String>,
    pub maxspeed: Option<String>,
    pub name: Option<String>,
    #[serde(rename = "ref")]
    pub ref_field: Option<String>,
    pub surface: Option<String>,
    #[serde(rename = "turn:lanes:backward")]
    pub turn_lanes_backward: Option<String>,
    #[serde(rename = "turn:lanes:forward")]
    pub turn_lanes_forward: Option<String>,
    pub bridge: Option<String>,
    pub layer: Option<String>,
    pub smoothness: Option<String>,
    pub tracktype: Option<String>,
    #[serde(rename = "man_made")]
    pub man_made: Option<String>,
    pub source: Option<String>,
    pub noname: Option<String>,
    pub bicycle: Option<String>,
    pub operator: Option<String>,
    #[serde(rename = "operator:abbr")]
    pub operator_abbr: Option<String>,
    #[serde(rename = "operator:website")]
    pub operator_website: Option<String>,
    #[serde(rename = "operator:wikipedia")]
    pub operator_wikipedia: Option<String>,
    pub construction: Option<String>,
    #[serde(rename = "alt_name:ru")]
    pub alt_name_ru: Option<String>,
    #[serde(rename = "cycleway:left")]
    pub cycleway_left: Option<String>,
    #[serde(rename = "cycleway:right")]
    pub cycleway_right: Option<String>,
    #[serde(rename = "name:etymology")]
    pub name_etymology: Option<String>,
    #[serde(rename = "name:etymology:wikidata")]
    pub name_etymology_wikidata: Option<String>,
    #[serde(rename = "name:lv")]
    pub name_lv: Option<String>,
    #[serde(rename = "name:ru")]
    pub name_ru: Option<String>,
    #[serde(rename = "old_name")]
    pub old_name: Option<String>,
    #[serde(rename = "old_name:etymology")]
    pub old_name_etymology: Option<String>,
    #[serde(rename = "old_name:etymology:description")]
    pub old_name_etymology_description: Option<String>,
    #[serde(rename = "old_name:etymology:description:lv")]
    pub old_name_etymology_description_lv: Option<String>,
    #[serde(rename = "old_name:etymology:description:ru")]
    pub old_name_etymology_description_ru: Option<String>,
    #[serde(rename = "old_name:etymology:wikidata")]
    pub old_name_etymology_wikidata: Option<String>,
    #[serde(rename = "old_name:lv")]
    pub old_name_lv: Option<String>,
    #[serde(rename = "old_name:ru")]
    pub old_name_ru: Option<String>,
    #[serde(rename = "oneway:bicycle")]
    pub oneway_bicycle: Option<String>,
    #[serde(rename = "oneway:bus")]
    pub oneway_bus: Option<String>,
    pub psv: Option<String>,
    #[serde(rename = "sidewalk:both")]
    pub sidewalk_both: Option<String>,
    #[serde(rename = "trolley_wire")]
    pub trolley_wire: Option<String>,
    pub wikidata: Option<String>,
    pub cycleway: Option<String>,
    pub lit: Option<String>,
    #[serde(rename = "sidewalk:left")]
    pub sidewalk_left: Option<String>,
    #[serde(rename = "sidewalk:right")]
    pub sidewalk_right: Option<String>,
    pub sidewalk: Option<String>,
    #[serde(rename = "maxspeed:hgv")]
    pub maxspeed_hgv: Option<String>,
    #[serde(rename = "maxspeed:type")]
    pub maxspeed_type: Option<String>,
    #[serde(rename = "embedded_rails:lanes:backward")]
    pub embedded_rails_lanes_backward: Option<String>,
    #[serde(rename = "embedded_rails:lanes:forward")]
    pub embedded_rails_lanes_forward: Option<String>,
    #[serde(rename = "name:de")]
    pub name_de: Option<String>,
    pub access: Option<String>,
    pub hgv: Option<String>,
    #[serde(rename = "parking:both")]
    pub parking_both: Option<String>,
    pub width: Option<String>,
    #[serde(rename = "cycleway:both")]
    pub cycleway_both: Option<String>,
    #[serde(rename = "lane_markings")]
    pub lane_markings: Option<String>,
    #[serde(rename = "parking:left")]
    pub parking_left: Option<String>,
    #[serde(rename = "parking:right")]
    pub parking_right: Option<String>,
    #[serde(rename = "parking:right:orientation")]
    pub parking_right_orientation: Option<String>,
    #[serde(rename = "parking:left:orientation")]
    pub parking_left_orientation: Option<String>,
    #[serde(rename = "parking:both:orientation")]
    pub parking_both_orientation: Option<String>,
    pub junction: Option<String>,
    pub footway: Option<String>,
    #[serde(rename = "hgv:forward")]
    pub hgv_forward: Option<String>,
    pub maxweight: Option<String>,
    pub proposed: Option<String>,
    pub maxheight: Option<String>,
    pub incline: Option<String>,
    #[serde(rename = "lanes:psv")]
    pub lanes_psv: Option<String>,
    #[serde(rename = "source:maxspeed")]
    pub source_maxspeed: Option<String>,
    #[serde(rename = "turn:lanes")]
    pub turn_lanes: Option<String>,
    pub bus: Option<String>,
    #[serde(rename = "tactile_paving")]
    pub tactile_paving: Option<String>,
    #[serde(rename = "maxspeed:backward")]
    pub maxspeed_backward: Option<String>,
    #[serde(rename = "maxspeed:forward")]
    pub maxspeed_forward: Option<String>,
    #[serde(rename = "name:en")]
    pub name_en: Option<String>,
    pub wikipedia: Option<String>,
    #[serde(rename = "motor_vehicle")]
    pub motor_vehicle: Option<String>,
    #[serde(rename = "addr:city")]
    pub addr_city: Option<String>,
    #[serde(rename = "addr:country")]
    pub addr_country: Option<String>,
    #[serde(rename = "addr:housenumber")]
    pub addr_housenumber: Option<String>,
    #[serde(rename = "addr:postcode")]
    pub addr_postcode: Option<String>,
    #[serde(rename = "addr:street")]
    pub addr_street: Option<String>,
    pub building: Option<String>,
    #[serde(rename = "ref:LV:addr")]
    pub ref_lv_addr: Option<String>,
    pub wheelchair: Option<String>,
    #[serde(rename = "lanes:psv:forward")]
    pub lanes_psv_forward: Option<String>,
    #[serde(rename = "parking:both:restriction")]
    pub parking_both_restriction: Option<String>,
    pub embankment: Option<String>,
    #[serde(rename = "sidewalk:both:surface")]
    pub sidewalk_both_surface: Option<String>,
    #[serde(rename = "alt_name")]
    pub alt_name: Option<String>,
    pub shoulder: Option<String>,
    pub vehicle: Option<String>,
    #[serde(rename = "check_date")]
    pub check_date: Option<String>,
    #[serde(rename = "historic:ref")]
    pub historic_ref: Option<String>,
    #[serde(rename = "embedded_rails")]
    pub embedded_rails: Option<String>,
    pub frequency: Option<String>,
    pub voltage: Option<String>,
    #[serde(rename = "roller_ski")]
    pub roller_ski: Option<String>,
    #[serde(rename = "priority_road")]
    pub priority_road: Option<String>,
    #[serde(rename = "maxweight:signed")]
    pub maxweight_signed: Option<String>,
    pub sport: Option<String>,
    pub fixme: Option<String>,
    #[serde(rename = "maxspeed:lanes")]
    pub maxspeed_lanes: Option<String>,
    pub mtb: Option<String>,
    #[serde(rename = "lane_spec")]
    pub lane_spec: Option<String>,
    #[serde(rename = "oneway:psv")]
    pub oneway_psv: Option<String>,
    #[serde(rename = "parking:lane:right")]
    pub parking_lane_right: Option<String>,
    #[serde(rename = "maxheight:signed")]
    pub maxheight_signed: Option<String>,
    pub electrified: Option<String>,
    pub gauge: Option<String>,
    pub railway: Option<String>,
    pub usage: Option<String>,
    #[serde(rename = "sac_scale")]
    pub sac_scale: Option<String>,
    #[serde(rename = "trail_visibility")]
    pub trail_visibility: Option<String>,
    #[serde(rename = "alt_name:source")]
    pub alt_name_source: Option<String>,
    #[serde(rename = "name:source")]
    pub name_source: Option<String>,
    #[serde(rename = "start_date")]
    pub start_date: Option<String>,
    #[serde(rename = "destination:backward")]
    pub destination_backward: Option<String>,
    #[serde(rename = "destination:forward")]
    pub destination_forward: Option<String>,
    pub overtaking: Option<String>,
    #[serde(rename = "public_transport")]
    pub public_transport: Option<String>,
    #[serde(rename = "maxspeed:conditional")]
    pub maxspeed_conditional: Option<String>,
    pub ski: Option<String>,
    #[serde(rename = "maxspeed:advisory")]
    pub maxspeed_advisory: Option<String>,
    #[serde(rename = "surface:note")]
    pub surface_note: Option<String>,
    #[serde(rename = "lanes:psv:backward")]
    pub lanes_psv_backward: Option<String>,
    pub planned: Option<String>,
    pub informal: Option<String>,
    pub note: Option<String>,
    #[serde(rename = "source:name")]
    pub source_name: Option<String>,
    #[serde(rename = "name:uk")]
    pub name_uk: Option<String>,
    #[serde(rename = "traffic_calming")]
    pub traffic_calming: Option<String>,
    pub service: Option<String>,
    pub covered: Option<String>,
    pub tunnel: Option<String>,
    #[serde(rename = "surface:lanes:backward")]
    pub surface_lanes_backward: Option<String>,
    #[serde(rename = "surface:lanes:forward")]
    pub surface_lanes_forward: Option<String>,
    #[serde(rename = "vehicle:lanes:backward")]
    pub vehicle_lanes_backward: Option<String>,
    #[serde(rename = "vehicle:lanes:forward")]
    pub vehicle_lanes_forward: Option<String>,
    #[serde(rename = "parking:right:restriction")]
    pub parking_right_restriction: Option<String>,
    #[serde(rename = "check_date:surface")]
    pub check_date_surface: Option<String>,
    #[serde(rename = "cycleway:both:lane")]
    pub cycleway_both_lane: Option<String>,
    #[serde(rename = "piste:difficulty")]
    pub piste_difficulty: Option<String>,
    #[serde(rename = "piste:grooming")]
    pub piste_grooming: Option<String>,
    #[serde(rename = "piste:type")]
    pub piste_type: Option<String>,
    #[serde(rename = "description:lv")]
    pub description_lv: Option<String>,
    #[serde(rename = "piste:abandoned")]
    pub piste_abandoned: Option<String>,
    #[serde(rename = "hgv:conditional")]
    pub hgv_conditional: Option<String>,
    #[serde(rename = "psv:lanes:forward")]
    pub psv_lanes_forward: Option<String>,
    #[serde(rename = "name:et")]
    pub name_et: Option<String>,
    #[serde(rename = "name:vro")]
    pub name_vro: Option<String>,
    pub roundabout: Option<String>,
    pub website: Option<String>,
    pub horse: Option<String>,
    #[serde(rename = "parking:left:restriction")]
    pub parking_left_restriction: Option<String>,
    pub noexit: Option<String>,
    #[serde(rename = "sidewalk:left:surface")]
    pub sidewalk_left_surface: Option<String>,
    #[serde(rename = "parking:both:restriction:conditional")]
    pub parking_both_restriction_conditional: Option<String>,
    pub area: Option<String>,
    #[serde(rename = "cycleway:lane")]
    pub cycleway_lane: Option<String>,
    #[serde(rename = "description:de")]
    pub description_de: Option<String>,
    pub shelter: Option<String>,
    #[serde(rename = "name:etymology:wikipedia")]
    pub name_etymology_wikipedia: Option<String>,
    pub destination: Option<String>,
    #[serde(rename = "destination:ref")]
    pub destination_ref: Option<String>,
    #[serde(rename = "name:fr")]
    pub name_fr: Option<String>,
    pub motorcar: Option<String>,
    pub bench: Option<String>,
    pub bin: Option<String>,
    #[serde(rename = "abandoned:highway")]
    pub abandoned_highway: Option<String>,
    #[serde(rename = "maxspeed:conditional:type")]
    pub maxspeed_conditional_type: Option<String>,
    pub trolleybus: Option<String>,
    pub grade: Option<String>,
    pub maxlength: Option<String>,
    #[serde(rename = "source:width")]
    pub source_width: Option<String>,
    #[serde(rename = "old_name:etymology:wikipedia")]
    pub old_name_etymology_wikipedia: Option<String>,
    #[serde(rename = "mtb:scale")]
    pub mtb_scale: Option<String>,
    #[serde(rename = "official_name")]
    pub official_name: Option<String>,
    pub toll: Option<String>,
    pub ford: Option<String>,
    #[serde(rename = "4wd_only")]
    pub n4wd_only: Option<String>,
    #[serde(rename = "toll:bicycle")]
    pub toll_bicycle: Option<String>,
    #[serde(rename = "toll:conditional")]
    pub toll_conditional: Option<String>,
    #[serde(rename = "toll:electric_vehicle")]
    pub toll_electric_vehicle: Option<String>,
    #[serde(rename = "bicycle:backward")]
    pub bicycle_backward: Option<String>,
    #[serde(rename = "construction_start_expected")]
    pub construction_start_expected: Option<String>,
    #[serde(rename = "vehicle:backward")]
    pub vehicle_backward: Option<String>,
    #[serde(rename = "alt_name:et")]
    pub alt_name_et: Option<String>,
    #[serde(rename = "alt_name:vro")]
    pub alt_name_vro: Option<String>,
    #[serde(rename = "sidewalk:right:surface")]
    pub sidewalk_right_surface: Option<String>,
    #[serde(rename = "old_alt_name:ru")]
    pub old_alt_name_ru: Option<String>,
    #[serde(rename = "flood_prone")]
    pub flood_prone: Option<String>,
    pub motorcycle: Option<String>,
    #[serde(rename = "parking:left:fee")]
    pub parking_left_fee: Option<String>,
    #[serde(rename = "parking:left:fee:conditional")]
    pub parking_left_fee_conditional: Option<String>,
    #[serde(rename = "parking:left:zone")]
    pub parking_left_zone: Option<String>,
    pub disused: Option<String>,
    pub obstacle: Option<String>,
    pub agricultural: Option<String>,
    #[serde(rename = "source:noname")]
    pub source_noname: Option<String>,
    #[serde(rename = "destination:symbol")]
    pub destination_symbol: Option<String>,
    #[serde(rename = "surface:grade")]
    pub surface_grade: Option<String>,
    pub distance: Option<String>,
    pub branch: Option<String>,
    #[serde(rename = "SHAPE_LEN")]
    pub shape_len: Option<String>,
    #[serde(rename = "old_name:1950-1989")]
    pub old_name_1950_1989: Option<String>,
    #[serde(rename = "old_name:lv:1950-1989")]
    pub old_name_lv_1950_1989: Option<String>,
    #[serde(rename = "old_name:ru:1950-1989")]
    pub old_name_ru_1950_1989: Option<String>,
    #[serde(rename = "parking:right:fee")]
    pub parking_right_fee: Option<String>,
    #[serde(rename = "parking:right:fee:conditional")]
    pub parking_right_fee_conditional: Option<String>,
    #[serde(rename = "parking:right:markings")]
    pub parking_right_markings: Option<String>,
    #[serde(rename = "parking:right:zone")]
    pub parking_right_zone: Option<String>,
    #[serde(rename = "old_name:1941-1941")]
    pub old_name_1941_1941: Option<String>,
    #[serde(rename = "old_name:1941-1944")]
    pub old_name_1941_1944: Option<String>,
    #[serde(rename = "old_name:1944-1990")]
    pub old_name_1944_1990: Option<String>,
    #[serde(rename = "old_name:1990-2008")]
    pub old_name_1990_2008: Option<String>,
    #[serde(rename = "old_name:de:1941-1944")]
    pub old_name_de_1941_1944: Option<String>,
    #[serde(rename = "old_name:lv:1941-1941")]
    pub old_name_lv_1941_1941: Option<String>,
    #[serde(rename = "old_name:lv:1941-1944")]
    pub old_name_lv_1941_1944: Option<String>,
    #[serde(rename = "old_name:lv:1944-1990")]
    pub old_name_lv_1944_1990: Option<String>,
    #[serde(rename = "old_name:lv:1990-2008")]
    pub old_name_lv_1990_2008: Option<String>,
    #[serde(rename = "old_name:ru:1941-1941")]
    pub old_name_ru_1941_1941: Option<String>,
    #[serde(rename = "old_name:ru:1944-1990")]
    pub old_name_ru_1944_1990: Option<String>,
    #[serde(rename = "old_name:ru:1990-2008")]
    pub old_name_ru_1990_2008: Option<String>,
    pub abandoned: Option<String>,
    #[serde(rename = "source:incline")]
    pub source_incline: Option<String>,
    #[serde(rename = "bus_bay")]
    pub bus_bay: Option<String>,
    #[serde(rename = "psv:lanes")]
    pub psv_lanes: Option<String>,
    #[serde(rename = "bridge:structure")]
    pub bridge_structure: Option<String>,
    #[serde(rename = "cycleway:width")]
    pub cycleway_width: Option<String>,
    #[serde(rename = "footway:width")]
    pub footway_width: Option<String>,
    pub segregated: Option<String>,
    #[serde(rename = "low_precision")]
    pub low_precision: Option<String>,
    #[serde(rename = "name:left")]
    pub name_left: Option<String>,
    #[serde(rename = "name:right")]
    pub name_right: Option<String>,
    pub email: Option<String>,
    pub phone: Option<String>,
    pub cutting: Option<String>,
    #[serde(rename = "maxspeed:individual_traffic")]
    pub maxspeed_individual_traffic: Option<String>,
    #[serde(rename = "maxspeed:motorcar")]
    pub maxspeed_motorcar: Option<String>,
    #[serde(rename = "maxspeed:motorcycle")]
    pub maxspeed_motorcycle: Option<String>,
    #[serde(rename = "motor_vehicle:forward")]
    pub motor_vehicle_forward: Option<String>,
    #[serde(rename = "motor_vehicle:forward:conditional")]
    pub motor_vehicle_forward_conditional: Option<String>,
    #[serde(rename = "maxspeed:backward:conditional")]
    pub maxspeed_backward_conditional: Option<String>,
    pub indoor: Option<String>,
    #[serde(rename = "parking:condition:both")]
    pub parking_condition_both: Option<String>,
    #[serde(rename = "parking:lane:both")]
    pub parking_lane_both: Option<String>,
    #[serde(rename = "parking:condition:right")]
    pub parking_condition_right: Option<String>,
    #[serde(rename = "parking:lane:left")]
    pub parking_lane_left: Option<String>,
    #[serde(rename = "parking:lane:left:parallel")]
    pub parking_lane_left_parallel: Option<String>,
    #[serde(rename = "opening_date")]
    pub opening_date: Option<String>,
    #[serde(rename = "parking:left:restriction:conditional")]
    pub parking_left_restriction_conditional: Option<String>,
    #[serde(rename = "check_date:smoothness")]
    pub check_date_smoothness: Option<String>,
    #[serde(rename = "bicycle:forward")]
    pub bicycle_forward: Option<String>,
    #[serde(rename = "parking:both:access")]
    pub parking_both_access: Option<String>,
    #[serde(rename = "cycleway:right:oneway")]
    pub cycleway_right_oneway: Option<String>,
    #[serde(rename = "alt_name_1")]
    pub alt_name_1: Option<String>,
    pub cyclestreet: Option<String>,
    pub description: Option<String>,
    #[serde(rename = "cycleway:right:surface")]
    pub cycleway_right_surface: Option<String>,
    #[serde(rename = "sidewalk:right:bicycle")]
    pub sidewalk_right_bicycle: Option<String>,
    pub intermittent: Option<String>,
    #[serde(rename = "parking:lane:right:diagonal")]
    pub parking_lane_right_diagonal: Option<String>,
    pub motorroad: Option<String>,
    #[serde(rename = "name:ar")]
    pub name_ar: Option<String>,
    #[serde(rename = "name:cs")]
    pub name_cs: Option<String>,
    #[serde(rename = "name:da")]
    pub name_da: Option<String>,
    #[serde(rename = "name:el")]
    pub name_el: Option<String>,
    #[serde(rename = "name:es")]
    pub name_es: Option<String>,
    #[serde(rename = "name:fi")]
    pub name_fi: Option<String>,
    #[serde(rename = "name:ga")]
    pub name_ga: Option<String>,
    #[serde(rename = "name:hr")]
    pub name_hr: Option<String>,
    #[serde(rename = "name:hu")]
    pub name_hu: Option<String>,
    #[serde(rename = "name:it")]
    pub name_it: Option<String>,
    #[serde(rename = "name:ja")]
    pub name_ja: Option<String>,
    #[serde(rename = "name:lb")]
    pub name_lb: Option<String>,
    #[serde(rename = "name:mk")]
    pub name_mk: Option<String>,
    #[serde(rename = "name:mt")]
    pub name_mt: Option<String>,
    #[serde(rename = "name:nl")]
    pub name_nl: Option<String>,
    #[serde(rename = "name:no")]
    pub name_no: Option<String>,
    #[serde(rename = "name:pl")]
    pub name_pl: Option<String>,
    #[serde(rename = "name:pt")]
    pub name_pt: Option<String>,
    #[serde(rename = "name:ro")]
    pub name_ro: Option<String>,
    #[serde(rename = "name:sk")]
    pub name_sk: Option<String>,
    #[serde(rename = "name:sl")]
    pub name_sl: Option<String>,
    #[serde(rename = "name:sr")]
    pub name_sr: Option<String>,
    #[serde(rename = "name:sv")]
    pub name_sv: Option<String>,
    #[serde(rename = "name:tr")]
    pub name_tr: Option<String>,
    #[serde(rename = "name:zh")]
    pub name_zh: Option<String>,
    #[serde(rename = "old_name:1867-1885")]
    pub old_name_1867_1885: Option<String>,
    #[serde(rename = "old_name:1885-1941")]
    pub old_name_1885_1941: Option<String>,
    #[serde(rename = "old_name:1885-2022-03-09")]
    pub old_name_1885_2022_03_09: Option<String>,
    #[serde(rename = "old_name:1941-1942")]
    pub old_name_1941_1942: Option<String>,
    #[serde(rename = "old_name:1942-1944")]
    pub old_name_1942_1944: Option<String>,
    #[serde(rename = "old_name:1944-1994")]
    pub old_name_1944_1994: Option<String>,
    #[serde(rename = "old_name:1994-2022-03-09")]
    pub old_name_1994_2022_03_09: Option<String>,
    #[serde(rename = "old_name:etymology:1941-1942")]
    pub old_name_etymology_1941_1942: Option<String>,
    #[serde(rename = "old_name:etymology:1944-1994")]
    pub old_name_etymology_1944_1994: Option<String>,
    #[serde(rename = "old_name:etymology:wikidata:1941-1942")]
    pub old_name_etymology_wikidata_1941_1942: Option<String>,
    #[serde(rename = "old_name:etymology:wikidata:1944-1994")]
    pub old_name_etymology_wikidata_1944_1994: Option<String>,
    #[serde(rename = "old_name:lv:1885-1941")]
    pub old_name_lv_1885_1941: Option<String>,
    #[serde(rename = "old_name:lv:1941-1942")]
    pub old_name_lv_1941_1942: Option<String>,
    #[serde(rename = "old_name:lv:1944-1994")]
    pub old_name_lv_1944_1994: Option<String>,
    #[serde(rename = "old_name:lv:1994-2022-03-09")]
    pub old_name_lv_1994_2022_03_09: Option<String>,
    #[serde(rename = "old_name:ru:1885-1941")]
    pub old_name_ru_1885_1941: Option<String>,
    #[serde(rename = "old_name:ru:1941-1942")]
    pub old_name_ru_1941_1942: Option<String>,
    #[serde(rename = "old_name:ru:1944-1994")]
    pub old_name_ru_1944_1994: Option<String>,
    #[serde(rename = "name:lt")]
    pub name_lt: Option<String>,
    #[serde(rename = "ncn_ref")]
    pub ncn_ref: Option<String>,
    #[serde(rename = "piste:oneway")]
    pub piste_oneway: Option<String>,
    #[serde(rename = "access:hgv")]
    pub access_hgv: Option<String>,
    #[serde(rename = "parking:condition:left")]
    pub parking_condition_left: Option<String>,
    #[serde(rename = "parking:lane:both:parallel")]
    pub parking_lane_both_parallel: Option<String>,
    #[serde(rename = "parking:lane:right:parallel")]
    pub parking_lane_right_parallel: Option<String>,
    #[serde(rename = "placement:forward")]
    pub placement_forward: Option<String>,
    #[serde(rename = "width:lanes:backward")]
    pub width_lanes_backward: Option<String>,
    #[serde(rename = "width:lanes:forward")]
    pub width_lanes_forward: Option<String>,
    #[serde(rename = "access:lanes:forward")]
    pub access_lanes_forward: Option<String>,
    #[serde(rename = "change:lanes:forward")]
    pub change_lanes_forward: Option<String>,
    pub turn: Option<String>,
    #[serde(rename = "change:lanes:backward")]
    pub change_lanes_backward: Option<String>,
    #[serde(rename = "placement:backward")]
    pub placement_backward: Option<String>,
    #[serde(rename = "change:lanes")]
    pub change_lanes: Option<String>,
    #[serde(rename = "access:lanes:backward")]
    pub access_lanes_backward: Option<String>,
    #[serde(rename = "end_date")]
    pub end_date: Option<String>,
    pub condition: Option<String>,
    pub noref: Option<String>,
    #[serde(rename = "old_name:de")]
    pub old_name_de: Option<String>,
    #[serde(rename = "bridge:name")]
    pub bridge_name: Option<String>,
    #[serde(rename = "bridge:ref")]
    pub bridge_ref: Option<String>,
    pub truck: Option<String>,
    #[serde(rename = "access:conditional")]
    pub access_conditional: Option<String>,
    pub amenity: Option<String>,
    #[serde(rename = "drinking_water")]
    pub drinking_water: Option<String>,
    pub fee: Option<String>,
    pub parking: Option<String>,
    pub toilets: Option<String>,
    #[serde(rename = "source:maxweight")]
    pub source_maxweight: Option<String>,
    #[serde(rename = "proposed:int_ref")]
    pub proposed_int_ref: Option<String>,
    #[serde(rename = "proposed:ref")]
    pub proposed_ref: Option<String>,
    #[serde(rename = "departures_board")]
    pub departures_board: Option<String>,
    pub abutters: Option<String>,
    #[serde(rename = "opening_hours")]
    pub opening_hours: Option<String>,
    #[serde(rename = "abandoned:railway")]
    pub abandoned_railway: Option<String>,
    pub route: Option<String>,
    #[serde(rename = "parking:condition:left:maxstay")]
    pub parking_condition_left_maxstay: Option<String>,
    pub priority: Option<String>,
    pub historic: Option<String>,
    #[serde(rename = "maaamet:ETAK")]
    pub maaamet_etak: Option<String>,
    pub resource: Option<String>,
    pub narrow: Option<String>,
    #[serde(rename = "int_name")]
    pub int_name: Option<String>,
    #[serde(rename = "parking:lane:right:perpendicular")]
    pub parking_lane_right_perpendicular: Option<String>,
    #[serde(rename = "trolley_wire:backward")]
    pub trolley_wire_backward: Option<String>,
    #[serde(rename = "destination:distance")]
    pub destination_distance: Option<String>,
    pub snowmobile: Option<String>,
    #[serde(rename = "description:en")]
    pub description_en: Option<String>,
    #[serde(rename = "description:pl")]
    pub description_pl: Option<String>,
    #[serde(rename = "name_2")]
    pub name_2: Option<String>,
    pub placement: Option<String>,
    pub leisure: Option<String>,
    #[serde(rename = "disused:aeroway")]
    pub disused_aeroway: Option<String>,
    #[serde(rename = "check_date:tracktype")]
    pub check_date_tracktype: Option<String>,
    pub railing: Option<String>,
    #[serde(rename = "mtb:scale:imba")]
    pub mtb_scale_imba: Option<String>,
    #[serde(rename = "horse_scale")]
    pub horse_scale: Option<String>,
    #[serde(rename = "mtb:scale:uphill")]
    pub mtb_scale_uphill: Option<String>,
    #[serde(rename = "loc_name")]
    pub loc_name: Option<String>,
    pub lines: Option<String>,
    #[serde(rename = "abandoned:aeroway")]
    pub abandoned_aeroway: Option<String>,
    pub length: Option<String>,
    pub waterway: Option<String>,
    pub tram: Option<String>,
    #[serde(rename = "piste:grooming:priority")]
    pub piste_grooming_priority: Option<String>,
    #[serde(rename = "park_ride")]
    pub park_ride: Option<String>,
    pub supervised: Option<String>,
    pub taxi: Option<String>,
    #[serde(rename = "hgv:backward")]
    pub hgv_backward: Option<String>,
    #[serde(rename = "maxspeed:practical")]
    pub maxspeed_practical: Option<String>,
    #[serde(rename = "historic:gauge")]
    pub historic_gauge: Option<String>,
    #[serde(rename = "railway:-1997")]
    pub railway_1997: Option<String>,
    #[serde(rename = "railway:end_date")]
    pub railway_end_date: Option<String>,
    #[serde(rename = "parking:left:markings")]
    pub parking_left_markings: Option<String>,
    #[serde(rename = "step_count")]
    pub step_count: Option<String>,
    pub heritage: Option<String>,
    #[serde(rename = "website:de")]
    pub website_de: Option<String>,
    #[serde(rename = "website:en")]
    pub website_en: Option<String>,
    #[serde(rename = "website:ru")]
    pub website_ru: Option<String>,
    pub handrail: Option<String>,
    pub ramp: Option<String>,
    #[serde(rename = "ramp:stroller")]
    pub ramp_stroller: Option<String>,
    #[serde(rename = "cycleway:left:surface")]
    pub cycleway_left_surface: Option<String>,
    #[serde(rename = "historic:trolley_wire")]
    pub historic_trolley_wire: Option<String>,
    pub material: Option<String>,
    pub goods: Option<String>,
    pub seasonal: Option<String>,
    pub level: Option<String>,
    #[serde(rename = "destination:lanes:backward")]
    pub destination_lanes_backward: Option<String>,
    #[serde(rename = "living_street")]
    pub living_street: Option<String>,
    #[serde(rename = "check_date:sidewalk:surface")]
    pub check_date_sidewalk_surface: Option<String>,
    #[serde(rename = "traffic_sign")]
    pub traffic_sign: Option<String>,
    #[serde(rename = "parking:lane:right:capacity")]
    pub parking_lane_right_capacity: Option<String>,
    #[serde(rename = "parking:left:taxi")]
    pub parking_left_taxi: Option<String>,
    #[serde(rename = "parking:right:bus")]
    pub parking_right_bus: Option<String>,
    #[serde(rename = "parking:both:fee")]
    pub parking_both_fee: Option<String>,
    #[serde(rename = "parking:both:markings")]
    pub parking_both_markings: Option<String>,
    #[serde(rename = "parking:left:access")]
    pub parking_left_access: Option<String>,
    #[serde(rename = "parking:right:access")]
    pub parking_right_access: Option<String>,
    #[serde(rename = "parking:both:fee:conditional")]
    pub parking_both_fee_conditional: Option<String>,
    #[serde(rename = "parking:both:zone")]
    pub parking_both_zone: Option<String>,
    #[serde(rename = "alt_name:lv")]
    pub alt_name_lv: Option<String>,
    #[serde(rename = "lanes:left")]
    pub lanes_left: Option<String>,
    #[serde(rename = "lanes:right")]
    pub lanes_right: Option<String>,
    pub image: Option<String>,
    pub barrier: Option<String>,
    #[serde(rename = "vehicle:forward")]
    pub vehicle_forward: Option<String>,
    pub razed: Option<String>,
    #[serde(rename = "name:2020-")]
    pub name_2020: Option<String>,
    #[serde(rename = "maxspeed:source")]
    pub maxspeed_source: Option<String>,
    #[serde(rename = "parking:lane")]
    pub parking_lane: Option<String>,
    #[serde(rename = "inline_skates")]
    pub inline_skates: Option<String>,
    #[serde(rename = "oneway:delivery")]
    pub oneway_delivery: Option<String>,
    #[serde(rename = "parking:right:restriction:conditional")]
    pub parking_right_restriction_conditional: Option<String>,
    pub car: Option<String>,
    #[serde(rename = "temporary:access")]
    pub temporary_access: Option<String>,
    #[serde(rename = "temporary:date_off")]
    pub temporary_date_off: Option<String>,
    #[serde(rename = "temporary:date_on")]
    pub temporary_date_on: Option<String>,
    pub emergency: Option<String>,
    pub comment: Option<String>,
    #[serde(rename = "local_ref")]
    pub local_ref: Option<String>,
    #[serde(rename = "check_date:lit")]
    pub check_date_lit: Option<String>,
    #[serde(rename = "area:highway")]
    pub area_highway: Option<String>,
    #[serde(rename = "motor_vehicle:conditional")]
    pub motor_vehicle_conditional: Option<String>,
    #[serde(rename = "parking:lane:left:perpendicular")]
    pub parking_lane_left_perpendicular: Option<String>,
    #[serde(rename = "parking:both:staggered")]
    pub parking_both_staggered: Option<String>,
    #[serde(rename = "maxspeed:forward:conditional")]
    pub maxspeed_forward_conditional: Option<String>,
    #[serde(rename = "traffic_sign:direction")]
    pub traffic_sign_direction: Option<String>,
    #[serde(rename = "internet_access")]
    pub internet_access: Option<String>,
    #[serde(rename = "internet_access:fee")]
    pub internet_access_fee: Option<String>,
    #[serde(rename = "payment:cash")]
    pub payment_cash: Option<String>,
    #[serde(rename = "payment:mastercard")]
    pub payment_mastercard: Option<String>,
    #[serde(rename = "payment:visa")]
    pub payment_visa: Option<String>,
    pub direction: Option<String>,
    pub crossing: Option<String>,
    #[serde(rename = "crossing:markings")]
    pub crossing_markings: Option<String>,
    #[serde(rename = "crossing:island")]
    pub crossing_island: Option<String>,
    pub kerb: Option<String>,
    #[serde(rename = "road_marking")]
    pub road_marking: Option<String>,
    #[serde(rename = "crossing:signals")]
    pub crossing_signals: Option<String>,
    #[serde(rename = "button_operated")]
    pub button_operated: Option<String>,
    #[serde(rename = "traffic_signals:sound")]
    pub traffic_signals_sound: Option<String>,
    #[serde(rename = "traffic_signals:vibration")]
    pub traffic_signals_vibration: Option<String>,
    pub locked: Option<String>,
    #[serde(rename = "bicycle_bypass")]
    pub bicycle_bypass: Option<String>,
    pub open: Option<String>,
    #[serde(rename = "lift_gate:type")]
    pub lift_gate_type: Option<String>,
    #[serde(rename = "traffic_signals")]
    pub traffic_signals: Option<String>,
    #[serde(rename = "traffic_signals:direction")]
    pub traffic_signals_direction: Option<String>,
    #[serde(rename = "was:traffic_calming")]
    pub was_traffic_calming: Option<String>,
    #[serde(rename = "crossing_ref")]
    pub crossing_ref: Option<String>,
    #[serde(rename = "leaf_cycle")]
    pub leaf_cycle: Option<String>,
    #[serde(rename = "leaf_type")]
    pub leaf_type: Option<String>,
    pub natural: Option<String>,
    pub bollard: Option<String>,
    pub temporary: Option<String>,
    pub information: Option<String>,
    pub tourism: Option<String>,
    #[serde(rename = "was:barrier")]
    pub was_barrier: Option<String>,
    #[serde(rename = "check_date:crossing")]
    pub check_date_crossing: Option<String>,
    #[serde(rename = "destroyed:barrier")]
    pub destroyed_barrier: Option<String>,
    #[serde(rename = "cycle_barrier")]
    pub cycle_barrier: Option<String>,
    #[serde(rename = "cycle_barrier:installation")]
    pub cycle_barrier_installation: Option<String>,
    pub entrance: Option<String>,
    #[serde(rename = "swing_gate:type")]
    pub swing_gate_type: Option<String>,
    #[serde(rename = "was:railway")]
    pub was_railway: Option<String>,
    pub mapillary: Option<String>,
    #[serde(rename = "was:highway")]
    pub was_highway: Option<String>,
    pub manhole: Option<String>,
    #[serde(rename = "traffic_signals:countdown")]
    pub traffic_signals_countdown: Option<String>,
    pub raised: Option<String>,
    #[serde(rename = "proposed:highway")]
    pub proposed_highway: Option<String>,
    #[serde(rename = "survey:date")]
    pub survey_date: Option<String>,
    #[serde(rename = "cycleway:crossing:markings")]
    pub cycleway_crossing_markings: Option<String>,
    #[serde(rename = "footway:crossing:markings")]
    pub footway_crossing_markings: Option<String>,
    pub depth: Option<String>,
    pub height: Option<String>,
    #[serde(rename = "crossing:barrier")]
    pub crossing_barrier: Option<String>,
    #[serde(rename = "railway:historic")]
    pub railway_historic: Option<String>,
    pub colour: Option<String>,
    #[serde(rename = "artwork_type")]
    pub artwork_type: Option<String>,
    pub hazard: Option<String>,
    #[serde(rename = "crossing:light")]
    pub crossing_light: Option<String>,
    #[serde(rename = "disused:railway")]
    pub disused_railway: Option<String>,
    #[serde(rename = "reg_name")]
    pub reg_name: Option<String>,
    #[serde(rename = "block:count")]
    pub block_count: Option<String>,
    #[serde(rename = "crossing:bell")]
    pub crossing_bell: Option<String>,
    #[serde(rename = "check_date:tactile_paving")]
    pub check_date_tactile_paving: Option<String>,
    #[serde(rename = "speed_camera")]
    pub speed_camera: Option<String>,
    #[serde(rename = "bridge:support")]
    pub bridge_support: Option<String>,
    #[serde(rename = "gate:type")]
    pub gate_type: Option<String>,
    pub enforcement: Option<String>,
    #[serde(rename = "crossing:saltire")]
    pub crossing_saltire: Option<String>,
    pub ferry: Option<String>,
    pub boundary: Option<String>,
    #[serde(rename = "crossing:activation")]
    pub crossing_activation: Option<String>,
    #[serde(rename = "crossing:supervision")]
    pub crossing_supervision: Option<String>,
    #[serde(rename = "gtfs_id")]
    pub gtfs_id: Option<String>,
    pub observation: Option<String>,
    #[serde(rename = "tower:type")]
    pub tower_type: Option<String>,
    #[serde(rename = "bus_routes")]
    pub bus_routes: Option<String>,
    #[serde(rename = "sloped_curb")]
    pub sloped_curb: Option<String>,
    #[serde(rename = "route_ref")]
    pub route_ref: Option<String>,
    #[serde(rename = "maxheight:legal")]
    pub maxheight_legal: Option<String>,
    pub fireplace: Option<String>,
    #[serde(rename = "FIXME")]
    pub fixme2: Option<String>,
    pub place: Option<String>,
    #[serde(rename = "addr:district")]
    pub addr_district: Option<String>,
    #[serde(rename = "addr:housename")]
    pub addr_housename: Option<String>,
    #[serde(rename = "addr:subdistrict")]
    pub addr_subdistrict: Option<String>,
    #[serde(rename = "railway:switch:electric")]
    pub railway_switch_electric: Option<String>,
    #[serde(rename = "operator:ref")]
    pub operator_ref: Option<String>,
    #[serde(rename = "check_date:crossing:barrier")]
    pub check_date_crossing_barrier: Option<String>,
    pub stop: Option<String>,
    #[serde(rename = "colour:back")]
    pub colour_back: Option<String>,
    #[serde(rename = "name:azb")]
    pub name_azb: Option<String>,
    #[serde(rename = "name:grc")]
    pub name_grc: Option<String>,
    #[serde(rename = "name:pa")]
    pub name_pa: Option<String>,
    #[serde(rename = "name:ur")]
    pub name_ur: Option<String>,
    #[serde(rename = "locked:conditional")]
    pub locked_conditional: Option<String>,
    pub ele: Option<String>,
    #[serde(rename = "button_operated:bicycle")]
    pub button_operated_bicycle: Option<String>,
    #[serde(rename = "esr:user")]
    pub esr_user: Option<String>,
    #[serde(rename = "uic_ref")]
    pub uic_ref: Option<String>,
    #[serde(rename = "waterway:sign")]
    pub waterway_sign: Option<String>,
    #[serde(rename = "city_limit")]
    pub city_limit: Option<String>,
    #[serde(rename = "traffic_island")]
    pub traffic_island: Option<String>,
    #[serde(rename = "source_ref")]
    pub source_ref: Option<String>,
}

#[derive(Default, Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Member {
    #[serde(rename = "type")]
    pub type_field: String,
    #[serde(rename = "ref")]
    pub ref_field: u64,
    pub role: String,
}
