name: Cache Cargo on Main

on: 
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-unknown-linux-gnu

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false

    - name: Cache cargo and build files
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/
          ~/.cargo/git/
          target/
        key: ${{ runner.os }}-cargo
        restore-keys: |
          ${{ runner.os }}-cargo

    - name: Cache pnpm
      uses: actions/cache@v4
      with:
        path: |
          ~/.local/share/pnpm/store
          src/debug/viewer/ui/node_modules
        key: ${{ runner.os }}-pnpm
        restore-keys: |
          ${{ runner.os }}-pnpm

    - name: Install node_modules
      run: |
        cd src/debug/viewer/ui/
        pnpm install

    - name: Build UI
      run: |
        cd src/debug/viewer/ui/
        pnpm build

    - name: Run build
      run: cargo build
