name: Release 

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get Next Version
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
    
    - name: Update Cargo.toml Version
      run: |
        VERSION="${{ steps.semver.outputs.next }}"
        VERSION_CLEAN="${VERSION#v}"  # Remove leading 'v' if present
        sed -i "s/^version = .*/version = \"$VERSION_CLEAN\"/" Cargo.toml
        
    - name: Run tests
      run: cargo test
      
    - name: Build Release
      run: cargo build --release
      
    - name: Generate Release Notes
      run: |
        git log $(git describe --tags --abbrev=0 2>/dev/null || echo HEAD^)..HEAD --pretty=format:"* %s" > RELEASE_NOTES.md
        
    - name: Commit Version Update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Cargo.toml
        git commit -m "chore: bump version to ${{ steps.semver.outputs.next }}"
        git push origin main --tags

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.semver.outputs.next }}
        name: Release ${{ steps.semver.outputs.next }}
        body_path: RELEASE_NOTES.md
        files: |
          target/release/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
